const demoData = [
  {
    id: 1,
    title: 'Meeting For Business',
    date: 'Sat, 25 Dec 2023',
    startTime: '7:35 am',
    endTime: '8:30 am',
    note: 'Discuss quarterly goals and strategies.',
    assignedTo: ['John', 'Alice', 'Bob'],
  },
  {
    id: 2,
    title: 'Project Presentation',
    date: 'Mon, 3 Jan 2024',
    startTime: '2:00 pm',
    endTime: '3:30 pm',
    note: 'Present project progress to the team.',
    assignedTo: ['Alice', 'Eva'],
  },
  {
    id: 3,
    title: 'Client Call',
    date: 'Wed, 12 Jan 2024',
    startTime: '10:00 am',
    endTime: '11:00 am',
    note: 'Discuss client requirements and updates.',
    assignedTo: ['John', 'Bob', 'Eva'],
  },
  {
    id: 4,
    title: 'Team Lunch',
    date: 'Fri, 5 Feb 2024',
    startTime: '12:30 pm',
    endTime: '1:30 pm',
    note: 'Celebrate recent successes and milestones.',
    assignedTo: ['All'],
  },
  {
    id: 5,
    title: 'Product Demo',
    date: 'Thu, 18 Feb 2024',
    startTime: '3:00 pm',
    endTime: '4:00 pm',
    note: 'Demo new features to potential clients.',
    assignedTo: ['John', 'Alice', 'Eva'],
  },
  {
    id: 6,
    title: 'Client Meeting',
    date: 'Mon, 1 Mar 2024',
    startTime: '9:00 am',
    endTime: '10:00 am',
    note: 'Review project progress with the client.',
    assignedTo: ['John', 'Bob'],
  },
  {
    id: 7,
    title: 'Team Brainstorming',
    date: 'Wed, 10 Mar 2024',
    startTime: '10:00 am',
    endTime: '12:00 pm',
    note: 'Generate ideas for upcoming projects.',
    assignedTo: ['All'],
  },
  {
    id: 8,
    title: 'Quarterly Review',
    date: 'Fri, 26 Mar 2024',
    startTime: '9:30 am',
    endTime: '11:00 am',
    note: 'Review quarterly performance and set goals.',
    assignedTo: ['All'],
  },
  {
    id: 9,
    title: 'Task Planning Session',
    date: 'Tue, 6 Apr 2024',
    startTime: '2:00 pm',
    endTime: '3:00 pm',
    note: 'Plan tasks and priorities for the week.',
    assignedTo: ['All'],
  },
  {
    id: 10,
    title: 'Client Workshop',
    date: 'Wed, 21 Apr 2024',
    startTime: '1:00 pm',
    endTime: '4:00 pm',
    note: 'Conduct a workshop on new product features.',
    assignedTo: ['John', 'Alice', 'Eva'],
  },
  // Add more tasks as needed
];

export default demoData;
